create table membership (
    id bigint generated by default as identity primary key,
    client varchar(255),
    client_id varchar(255) not null,
    client_phone varchar(255),
    client_email varchar(255),
    vehicle_type varchar(255),
    plate varchar(255),
    periodicity varchar(255),
    fee integer not null
);

create table membership_billed (
    id bigint generated by default as identity primary key,
    membership_id bigint,
    billed_by varchar(255),
    billing_date timestamp,
    comment varchar(255)
);

create table membership_comment (
    id bigint generated by default as identity primary key,
    membership_id bigint,
    content varchar(255),
    id_posted_by bigint,
    creation_date timestamp
);

create table parking (
    id bigint generated by default as identity primary key,
    plate varchar(255) not null,
    entry_time timestamp,
    exit_time timestamp,
    charge integer not null,
    charged_by varchar(255),
    comment varchar(255)
);
